name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.7", "3.0"]
        jekyll-version: ["~> 3.0", "~> 4.0"]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
        env:
          JEKYLL_VERSION: ${{ matrix.jekyll-version }}

      - name: Install Dependencies
        run: bundle install

      - name: Build
        run: gem build

      - name: Release Gem
        if: contains(github.ref, 'refs/tags/v')
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake release
